desafiocielo-web:
  display-name: desafiocielo-web
  
server:
  port: ${PORT:8000}  
  
info:
  name: ${desafiocielo-web.display-name}
  version: 1.0
  
spring:
  banner:
    location: classpath:banner.txt
    
logging:
  level:
    org.springframework.web: ERROR
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file: logs/desafiocielo-web.log
    